### ISSUE TITLE
Missed setup of RENDERING_HINTS at ProgressiveBilinearResizer.java

### ISSUE THREAD

**Issue by LiomSV** [coobird/thumbnailator#107]
Look at net.coobird.thumbnailator.resizers.ProgressiveBilinearResizer line 74.
In case when multi-step downscaling is not required and one-step scaling is performed, it doesn't set RenderingHints to destination image.

It doesn't matter when you don't use the resizer directly, because resizer factory doesn't return this one in case of such image. But direct usage leads to worse quality, because no any interpolation hint is set.

So, my suggestion is to add:
`g.setRenderingHints(RENDERING_HINTS);`
after line 74 into ProgressiveBilinearResizer.java

**Comment by coobird** [comment]
@LiomSV, I've verified that this was indeed the case, and have committed a fix for it. It should be applied to the next Thumbnailator release. Once again, thank you! :)
