### ISSUE TITLE
Document `keepAspectRatio` in examples

### ISSUE THREAD

**Issue by vincentkerdraon** [coobird/thumbnailator#113]
## Expected behavior
Builder exists and works for argument : keepAspectRatio
(feature is precious because round on reduction will have a few pixel difference with requested size)
Example : expecting 500x1000px and got 499x1000px

## Actual behavior
keepAspectRatio arg is not mentioned in examples

##Suggestion of example
Thumbnails.of(dir_in.listFiles()).size(width, height).keepAspectRatio(false).
				.toFiles(dir_out, **Rename.NO_CHANGE);
This will take every picture in dir_in, and copy them in dir_out (same name, same extension). All pictures final widths will be exactly requested width and heigh.

_thx for this tool._

**Comment by coobird** [comment]
Definitely wouldn't hurt to mention it in the examples page. Thank you for the suggestion. :)

**Comment by coobird** [comment]
Added [an example](https://github.com/coobird/thumbnailator/wiki/Examples#forcing-thumbnails-to-be-exactly-the-specified-size) in the Examples page.
