### ISSUE TITLE
wrong dimensions for portrait images on production environment

### ISSUE THREAD

**Issue by santo74** [coobird/thumbnailator#117]
## Expected behavior
Executing the following code:
`Thumbnails.of(imgInputStream).useExifOrientation(true).size(newWidth, newHeight).outputFormat("jpg").outputQuality(quality).toOutputStream(os);`

given a newWidth of 350px and a newHeight of 662px for an image with an original width of 2160px and an original height of 3840px I would expect the resulting image to have a width of 350px and a height of 662px.

## Actual behavior
On my dev and test environments, the resulting image has a width of 350px and a height of 622px, as expected.

However, on my production environment the resulting image has a width of 197px and a height of 350px.
And because my application has to display all images in a box of 290px x 230px (w x h) the image is very blurred (obviously).

Images in landscape orientation seem to behave correctly however.

I also tried to use the forceSize() method.
On my dev and test environment this again results in the correct dimensions but on my production environment the image is now stretched (i.e. width > height while the original image is in portrait format, i.e. width < height)

## Steps to reproduce the behavior
I have no steps to reproduce the behaviour because the issue only occurs on my production environment, which has exactly the same versions of OS, JDK and thumbnailator as my dev and test environment (see below for details)

I have the impression that the width and height specified in the size() and forceSize() methods are somehow switched on my production environment for some reason I can't explain.

## Environment
- OS vendor and version: Ubuntu 16.04.2 LTS
- JDK vendor and version: tried 2 different JDK's:
1) OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
2) OpenJDK Runtime Environment (Zulu 8.21.0.1-linux64) (build 1.8.0_131-b11)
- Thumbnailator version: v0.4.8

**Comment by stefanwendelmann** [comment]
I got the exact same problem with v.0.4.17 and OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1) on Windows and same on Docker ubi8 image and java-11-openjdk-headless

**Comment by stefanwendelmann** [comment]
@santo74  & @coobird  i checked agin and saw that there was an exif orientation on my image.
So setting `useExifOrientation` to false keeps my selected width or height but the image is then landscape not portrait.

@coobird  would be nice if one coud use the exif Orientation and the prefered width and / or height doesent get flipped.

**Comment by coobird** [comment]
@stefanwendelmann, thanks for the details. I'm not exactly sure if you're reporting the same issue, but it sounds like #91 for sure. I'll try looking into this.

**Comment by coobird** [comment]
Closing, as #91 has been fixed.
