### ISSUE TITLE
Resize only if the original image is larger than the specified size?

### ISSUE THREAD

**Issue by bingqiao** [coobird/thumbnailator#119]
```
Thumbnails.of(inputStream)
        .size(480, 480)
        .toFile(filePath);
```

## Expected behavior
When the dimensions of  the original image are smaller than the specified size, the image should not be made larger.

## Actual behavior

For a jpg image of 120x120, the resulting file is 480x480.

**Comment by coobird** [comment]
Thank you for filing this issue.

This is basically very similar to #11, but achieved by changing the behavior of an existing function. Although the API for the `size(int, int)` method is a little bit vague about whether it will enlarge the image if the source image is smaller than the given dimensions, changing the behavior now would be too surprising to existing users, and will break the expectations of others who are depending on the _de facto_ behavior of that method.
