### ISSUE TITLE
Provide snapshot artifacts for in-development versions

### ISSUE THREAD

**Issue by cazacugmihai** [coobird/thumbnailator#121]
Is there a repository that holds the snapshot releases available for master/develop branches?

**Comment by coobird** [comment]
@cazacugmihai, sorry for the late reply.

There are no snapshot releases being made right now. However, that's actually a pretty good idea, since now that Thumbnailator has a `develop` branch, which didn't exist until recently. :)

**Comment by smiklosovic** [comment]
use jitpack https://jitpack.io/

**Comment by cazacugmihai** [comment]
Thank you!
