### ISSUE TITLE
Compress .png picture, the background's color turns black

### ISSUE THREAD

**Issue by fuyuciel** [coobird/thumbnailator#140]
Hello friends,
Before Compression, the background's color is transparent.
After Compression, the background's color is black.
The picture's format is png.
Thanks for yours answers.

**Comment by coobird** [comment]
Without any additional details, I'm guessing this is a duplicate of #41. There's a workaround mentioned toward the end of #41.

**Comment by coobird** [comment]
I'll close this as a duplicate of #41.
