### ISSUE TITLE
Unexpected alpha channel when using RGB colors and rotate

### ISSUE THREAD

**Issue by ArheusLis** [coobird/thumbnailator#157]
## Expected behavior
Output got rgb colors scheme.

## Actual behavior
If I'm using rotation even with 0 - output become 32bit ARGB.

## Steps to reproduce the behavior
            Thumbnails.of(new File("source_1.bmp"))
                    .imageType(BufferedImage.TYPE_INT_RGB).scale(1).rotate(0).outputFormat("PNG")
                    .toFile(new File("expect.png"));
Output: 32 bit ARGB

            Thumbnails.of(new File("source_1.bmp"))
                    .imageType(BufferedImage.TYPE_INT_RGB).scale(1).outputFormat("PNG")
                    .toFile(new File("expect.png"));
Output: 24 bit RGB

## Environment
- OS vendor and version: Windows 10
- JDK vendor and version: 11
- Thumbnailator version:0.4.12

**Comment by coobird** [comment]
@ArheusLis , thank you for reporting this.

This behavior seems to be incorrect.

**Comment by coobird** [comment]
Fixed in 0.4.13.
