### ISSUE TITLE
how can I save the exif to the new file?

### ISSUE THREAD

**Issue by 236xzl** [coobird/thumbnailator#158]
## Expected behavior
_Please describe what you are expecting the library to perform._

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:
- JDK vendor and version:
- Thumbnailator version:

**Comment by coobird** [comment]
@236xzl, as of now, there is no feature to retain the Exif information in the output file.

I'm closing this as there is a separate issue to address this. (#52)
