### ISSUE TITLE
Thumbnail image is always rotated, useExifOrientation parameter does not matter

### ISSUE THREAD

**Issue by dmitry-weirdo** [coobird/thumbnailator#159]
## Expected behavior
Image thumbnail is NOT rotated 90 degrees left.

## Actual behavior
If image has height more than width, it is rotated 90 degrees left.

![20200425_142028](https://user-images.githubusercontent.com/15837869/93612732-248dad80-f9d0-11ea-82fa-ecf2f37d787c.jpg)

![20200425_142028-thumbnail](https://user-images.githubusercontent.com/15837869/93612685-163f9180-f9d0-11ea-957e-275e3154b262.jpg)

Whatever combinations of `size`, `width`, `useExifOrientation`, `keepAspectRatio` I set, the thumbnail is rotated. Image size is also always the same.

Code example: 
```
    public static void generateThumbnail(File imageFile, File thumbnailFile, Integer width) {
        try {
            // First convert to BufferedImage
            BufferedImage bufferedImage = ImageIO.read(imageFile);

            // Make thumbnail
            Thumbnails
                .of(bufferedImage)
//                .size(THUMBNAIL_WIDTH, THUMBNAIL_WIDTH)
//                .keepAspectRatio(true)
//                .useExifOrientation(true)
                .width(width)
//                .height(width)
                .useExifOrientation(true)
                .outputFormat("jpg")
                .toFile(thumbnailFile);

            logger.debug("Thumbnail of image file {} generated to file {}", imageFile.getPath(), thumbnailFile.getPath());
        }
        catch (IOException e) {
            logger.error(String.format("Error while generating thumbnail of file %s to thumbnail file %s", imageFile.getPath(), thumbnailFile.getPath()), e);

            throw new RuntimeException(e);
        }
    }
```

## Steps to reproduce the behavior
See the "Actual Behavior" section

## Environment
- OS vendor and version: Microsoft Windows [Version 10.0.17134.1667]

- JDK vendor and version: 
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

- Thumbnailator version: 0.4.12

**Comment by dmitry-weirdo** [comment]
Looks like it's working for `File` and `InputStream`, but not working for `BufferedImage` of this file.

```
            BufferedImage bufferedImage = ImageIO.read(imageFile);

            InputStream inputStream = new FileInputStream(imageFile);

            // NOT rotated!           
            Thumbnails.of(inputStream)
                .width(width)
                .outputFormat("jpg")
                .toFile("c:\\java\\thumbnail-input-stream.jpg");

            // NOT rotated!           
            Thumbnails.of(imageFile)
                .width(width)
                .outputFormat("jpg")
                .toFile("c:\\java\\thumbnail-image-file.jpg");

            // Rotated :( 
            Thumbnails.of(bufferedImage)
                .width(width)
                .outputFormat("jpg")
                .toFile("c:\\java\\thumbnail-buffered-image.jpg");
```

![thumbnail-buffered-image](https://user-images.githubusercontent.com/15837869/93615009-27d66880-f9d3-11ea-9440-72734b95018a.jpg)
![thumbnail-image-file](https://user-images.githubusercontent.com/15837869/93615022-2ad15900-f9d3-11ea-8b78-04a2beff6ff7.jpg)
![thumbnail-input-stream](https://user-images.githubusercontent.com/15837869/93615857-3f622100-f9d4-11ea-91a8-2e8f135ad7e2.jpg)

**Comment by coobird** [comment]
@dmitry-weirdo, Exif is metadata that's stored in certain image files. A `BufferedImage` does not contain Exif information. If you want to use Exif-based rotation, you will need to use either the `File` or `InputStream` as the input.

**Comment by coobird** [comment]
I'm closing this issue as it is expected behavior. Please refer to my [previous comment](https://github.com/coobird/thumbnailator/issues/159#issuecomment-694978197) for why rotation based on Exif won't work in the code you originally posted.

**Comment by Boldbayar** [comment]
IT is also happening when i work with FIle aswell, 
`Thumbnails.of(targetLocation.toFile())
					.useExifOrientation(true)
					.size(320, 320)
					.keepAspectRatio(true)
					.outputFormat("jpg")
					.toFiles(Rename.PREFIX_DOT_THUMBNAIL);
					response.setThumbnailPath("thumbnail." + fileName);`
