### ISSUE TITLE
hey,when do you will refactor the core logic to support big pic?

### ISSUE THREAD

**Issue by LoveUpe** [coobird/thumbnailator#166]
## Expected behavior
_Please describe what you are expecting the library to perform._
at 0.4.8 version, you say u need some time to resfactor project to support big file. i wanna to know ,how long?:)

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:
- JDK vendor and version:
- Thumbnailator version:

**Comment by coobird** [comment]
Given I have a limited amount of time, fixing known bugs are given the highest priority. Rearchitecting to support large image files more effectively is lower in the list of priorities.
