### ISSUE TITLE
Take advantage of GitHub CI's free runners to build and test the project.

### ISSUE THREAD

**Issue by carldea** [coobird/thumbnailator#169]
## Enhancement
Build using GitHub CI instead of Travis or along with Travis.

The following is the PR that builds and tests whenever there is a push event.
https://github.com/coobird/thumbnailator/pull/168

**Comment by coobird** [comment]
Thanks for the suggestion. Since Thumbnailator targets Java 5+ (GitHub CI supports Java 8, 11 and 12 only), I'm running CI on a local system to exercise each of the targeted versions.

**Comment by carldea** [comment]
> Thanks for the suggestion. Since Thumbnailator targets Java 5+ (GitHub CI supports Java 8, 11 and 12 only), I'm running CI on a local system to exercise each of the targeted versions.

no problem. Actually zulu does support Java 6-18, but not 5 (i don't believe)
