### ISSUE TITLE
Offer thumbnailator under a standard open source license

### ISSUE THREAD

**Issue by chuckdumont** [coobird/thumbnailator#172]
## Expected behavior
thumbnailator is available under one or more of the standard open source licenses (e.g. Apache 2, MIT, etc.).

## Actual behavior
thumbnailator is only  available under a proprietary license.  This restricts it's use since many commercial products that use open source code don't want to deal with proprietary licenses.  I, for one, would love to use this package, but the company I work for won't approve it due to the license.

## Steps to reproduce the behavior
N/A
## Environment
N/A

**Comment by coobird** [comment]
Have you taken a look at [LICENSE](https://github.com/coobird/thumbnailator/blob/master/LICENSE)? Thumbnailator is licensed under an OSI-approved license.

**Comment by chuckdumont** [comment]
I did take a look.  I see a copyright statement and the terms of the license.  Note that it's not an issue with the license terms.  The terms you specify sound perfectly reasonable to me.  It's a book keeping issue.  Large companies like mine don't want to pay their lawyers to review and approve hundreds of individual licenses.  They have a list of licenses that have been pre-approved and can be used without further review.  Anything not on the pre-approved list triggers a time consuming review request process and is generally discouraged, particularly for one-off licenses like yours.  Even if the text of the license is substantially the same as an existing approved license, it still requires a lawyer to make that determination and approve the license.  Because getting new licenses approved can be cumbersome and time consuming, many programmers (myself included) will simply look for alternatives that have pre-approved licenses.

**Comment by coobird** [comment]
It's the MIT License. Not sure why this is considered a "one-off" license.

... Unless you're referring to the header line included at the top of `LICENSE`? If that's the case, I can consider removing it.

**Comment by coobird** [comment]
Pushed change to `master` which hopefully is a bit more clear that Thumbnailator is released under the MIT license.

**Comment by chuckdumont** [comment]
That actually makes all the difference.  Note that header that github now displays when viewing the license.  Thanks much.

**Comment by chuckdumont** [comment]
@coobird - any forecast on when we can get a new release with the license update?

**Comment by coobird** [comment]
@chuckdumont Hopefully in a day or two.
