### ISSUE TITLE
No suitable ImageReader found for source data.

### ISSUE THREAD

**Issue by zth1993** [coobird/thumbnailator#173]
## Expected behavior
_Please describe what you are expecting the library to perform._
when i toOutputStream a webp pic,that i has this error.

## Environment
- OS vendor and version:
- JDK vendor and version:  11.0.11
- Thumbnailator version:0.4.13

**Comment by coobird** [comment]
@zth1993, please refer to the [FAQ](https://github.com/coobird/thumbnailator/wiki/FAQ).

You can also find more context in terms of WebP in this [comment](https://github.com/coobird/thumbnailator/issues/137#issuecomment-578464544).
