### ISSUE TITLE
Rotate Caption / Watermark

### ISSUE THREAD

**Issue by rider87** [coobird/thumbnailator#178]
Hi, 

I want to rotate the text of my Watermark...
How is this possible?

Thanks

**Comment by coobird** [comment]
You could pre-rotate an image and use it as a watermark.

```java
// Pre-rotate image used as watermark.
BufferedImage watermark = Thumbnails.of("/path/to/watermark")
    .size(100, 100)
    .rotate(90)
    .asBufferedImage();

// Use the pre-rotated watermark to make thumbnail
Thumbnails.of("/path/to/image")
    .size(400, 400)
    .watermark(Positions.BOTTOM_RIGHT, watermark, 0.5f);
    .toFile("/path/to/thumbnail")
```

Generally, watermarks are static, so any kind of processing necessary on the watermark can be performed ahead of time. The `watermark` methods reflect that common use case.

**Comment by coobird** [comment]
Question answered. Closing for no follow-up activity.
