### ISSUE TITLE
How to add a watermark in text?

### ISSUE THREAD

**Issue by wraptor** [coobird/thumbnailator#180]
## Expected behavior
how can i make watermark , base on word,not image,like this 
i input string "example.com/xxxx", and generate watermark in image
![image](https://user-images.githubusercontent.com/52092701/138584207-fddf2c90-13e1-4aac-b799-6dd65c5b4a7e.png)

## Environment
- OS vendor and version: Win10
- JDK vendor and version: JDK8
- Thumbnailator version: 0.4.13

**Comment by coobird** [comment]
The [`Caption`](https://coobird.github.io/thumbnailator/javadoc/0.4.14/net/coobird/thumbnailator/filters/Caption.html) filter can be used to add text on an image. They can be added by using the `addFilter` method.

Here's an example:

```
Font font = ...
Color color = ...
Thumbnails.of("/path/to/image")
    .size(100, 100)
    .addFilter(new Caption("my text", font, color, 0.5f, Positions.BOTTOM_RIGHT, 5))
    .toFile("/path/to/thumbnail");
```

**Comment by wraptor** [comment]
thanks.
