### ISSUE TITLE
Does thumbnailator support thumbnail generation for pdf files?

### ISSUE THREAD

**Issue by bhupendersinghh** [coobird/thumbnailator#181]
I want to generate images for pdf files containing multiple pages. Is there a way to leverage thumbnailator for that?

**Comment by coobird** [comment]
Short answer is no.

Long answer is, if you're able to make a image from a PDF, then yes, you can use Thumbnailator to make a thumbnail of that image. I found [an answer in StackOverflow](https://stackoverflow.com/a/4995102) saying that [PDFBox](https://pdfbox.apache.org/) can create images, and it sure seems like [`PDFRenderer`](https://pdfbox.apache.org/docs/2.0.3/javadocs/org/apache/pdfbox/rendering/PDFRenderer.html) can create `BufferedImage`s that Thumbnailator can use as sources for making thumbnails.

**Comment by cluth17** [comment]
I was able to accomplish this with the following code:

```
public static Boolean processImage(Path input, Path output, Integer width, Integer height) {  

     PDDocument pdfDoc = PDDocument.load(new File(input.toString()));  
     PDFRenderer pdfRender = new PDFRenderer(pdfDoc);  
     BufferedImage pdfImage = pdfRender.renderImageWithDPI(0, 72);  
     Thumbnails.of(pdfImage).size(width, height).toFile(output.toString());  
     return true;  

}
```
