### ISSUE TITLE
No suitable ImageReader found for source data(jpeg Picture format)

### ISSUE THREAD

**Issue by devinliu1** [coobird/thumbnailator#197]
When using thumbnails to add watermarks

Thumbnails. of(inputStream). scale(1). outputQuality(1). toFile(filePath);

Throw exception net coobird. thumbnailator. tasks. UnsupportedFormatException: No suitable ImageReader found for source data

**Comment by coobird** [comment]
Thumbnailator relies on the Image I/O API's to read/write images. As such, the supported image formats depend on what's available to the Java environment. More information in [Which image formats are supported by Thumbnailator](https://github.com/coobird/thumbnailator/wiki/FAQ#which-image-formats-are-supported-by-thumbnailator))

My guess would be that the file you think is a JPEG is not actually a JPEG. (For example, maybe the file is some other format like WebP but has a `.jpg` extension.) I can only guess based on the limited information provided.

Once you do find out what kind of image format it is, I would refer you back to the [FAQ](https://github.com/coobird/thumbnailator/wiki/FAQ#which-image-formats-are-supported-by-thumbnailator) about supported image formats and see the next steps you can take.

**Comment by devinliu1** [comment]
Thank you. The problem has been solved
