### ISSUE TITLE
Do you have plans to support WebP, AVIF?

### ISSUE THREAD

**Issue by tsyma** [coobird/thumbnailator#199]
Just query: Do you have plans to support WebP and AVIF?
WebP is already supported by all web Browsers.
https://en.wikipedia.org/wiki/WebP
https://en.wikipedia.org/wiki/AVIF

**Comment by coobird** [comment]
The image reading and writing functionality of Thumbnailator is dependent on the capability of the Java Image I/O API which the library uses. Therefore, if you want support for WebP or AVIF, you'll need to use a Image I/O plugin that supports those formats. For example, the [TwelveMonkeys ImageIO](https://github.com/haraldk/TwelveMonkeys) library supports WebP.

For more information, please refer to [this FAQ](https://github.com/coobird/thumbnailator/wiki/FAQ#which-image-formats-are-supported-by-thumbnailator).
