### ISSUE TITLE
the .pict file is not supported

### ISSUE THREAD

**Issue by vulner910** [coobird/thumbnailator#209]
## Expected behavior
_Please describe what you are expecting the library to perform._

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:
- JDK vendor and version:
- Thumbnailator version:

**Comment by coobird** [comment]
@vulner910 , Thumbnailator relies on Image I/O plugins available at runtime for reading and writing images. The default Java environment doesn't have support for the PICT format, so Thumbnailator cannot handle them.

If you want to handle other image formats, you'll need to add the appropriate Image I/O plugins to support them. For example, if you need PICT support, [TwelveMonkeys ImageIO](https://github.com/haraldk/TwelveMonkeys) has support for them. You'll basically just need to [add a Maven dependency to the PICT plugin ("imageio-pict")](https://github.com/haraldk/TwelveMonkeys#maven-dependency-example) and that should be all you'll need to do.

For more information, please refer to the [FAQ on this topic](https://github.com/coobird/thumbnailator/wiki/FAQ#which-image-formats-are-supported-by-thumbnailator).
