### ISSUE TITLE
How to make the image width fixed when the image is scaled

### ISSUE THREAD

**Issue by epubreader** [coobird/thumbnailator#212]
How to make the width of the picture fixed and keep the original aspect ratio when the picture is scaled?

**Comment by coobird** [comment]
@epubreader, does the [`width`](https://coobird.github.io/thumbnailator/javadoc/0.4.20/net/coobird/thumbnailator/Thumbnails.Builder.html#width(int)) method accomplish what you want to do?

```java
Thumbnails.of("/path/to/image")
    .width(200)
    .toFile("/path/to/thumbnail");
```

In this example, the thumbnail will have a width of 200 pixels, while the height will be adjusted to maintain the aspect ratio of the original image.
