### ISSUE TITLE
JVM memory becomes high when generating thumbnails

### ISSUE THREAD

**Issue by zhangyidao** [coobird/thumbnailator#222]
## Expected behavior
_Please describe what you are expecting the library to perform._
I would like the memory not to go high. This looks like a memory leak.

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._
When I upload a 100Mb PSD file, when I generate thumbnails, the Java program memory increases from 700Mb to 1.5g, and it cannot be recovered. 
I have observed this for a day.

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._
```
BufferedImage thumbnail = Thumbnails.of(is)
                .width(width)
                .asBufferedImage();
```
Every time I execute here, the memory rises very high.

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version: ubuntu 20.4
- JDK vendor and version: jdk1.8
- Thumbnailator version: 0.4.20

**Comment by okmilo** [comment]
Regarding the G1 garbage collector, it keeps expanding memory, and setting -Xmx doesn’t help
