### ISSUE TITLE
Exception reading a CMYK Jpeg

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#40]
```
What steps will reproduce the problem?
1. Generate a CMYK JPG, call it selectedFile
1. Run Thumbnails.of(selectedFile).size(500, 500).toFile(thumb500File);

What is the expected output? What do you see instead?

Expected output - thumb500File created normally

Actual output: Exception raised "Incompatible color conversion"

What version of the product are you using? On what operating system? Which
version of Java (Sun/Oracle? OpenJDK?) ?

OpenJDK 7u9, Ubuntu Linux

Please provide any additional information below.

The core Java method ImageIO.read produces exactly the same exception, e.g.

BufferedImage originalImage = ImageIO.read(selectedFile);

so it looks like the issue is with Java, however other people have found 
workarounds - 
http://www.randelshofer.ch/blog/2011/08/reading-cmyk-jpeg-images-with-java-image
io/

Would it be possible to implement a workaround in Thumbnailator too? I think 
the Java issue dates back some time.

A sample JPG exhibiting the problem is attached.

```

Original issue reported on code.google.com by `oliver.k...@gmail.com` on 1 Nov 2012 at 12:59

Attachments:
- [cmyk_sample.jpg](https://storage.googleapis.com/google-code-attachments/thumbnailator/issue-40/comment-0/cmyk_sample.jpg)

**Comment by Paper-Folding** [comment]
I encountered the same problem, if converting image to rgb via photoshop, the problem disappears.

**Comment by coobird** [comment]
Support for CMYK JPEGs would require writing a JPEG reader that supports it, which is outside the scope of Thumbnailator. (Thumbnailator is a wrapper around the Java 2D and Image I/O APIs.)

[TwelveMonkeys ImageIO](https://github.com/haraldk/TwelveMonkeys) provides an excellent alternative to Java's default JPEG reader/writer, which can deal with CMYK JPEGs
