### ISSUE TITLE
Unexpected behaviour when using toFile without an extension matching output format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#66]
```
Take this small code block:

File inputFile = new File("...");
File outputFile = File.createTempFile("thumbnail", null);
Thumbnails.of(inputFile).size(100,100).outputFormat("jpg").toFile(outputFile);

My expected result is that outputFile contains the thumbnail, which I think is 
reasonable and in line with the javadocs of toFile. However, Thumbnailator 
writes the thumbnail to a new file with .jpg appended, which isn't exposed 
anywhere, so my code in principle has no way of accessing the thumbnail without 
knowledge of the internal implementation.

Obviously this is easy enough to work around by creating the temp file with a 
.jpg extension, but this really shouldn't be needed.
```

Original issue reported on code.google.com by `bjmac...@gmail.com` on 19 Feb 2014 at 8:15

**Comment by shillem** [comment]
I have tried to apply the suggested snippet but without success. Another exception is thrown for a temporary file whose name doesn't include any extension.

`net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for /var/ibm/domino/data/xspupload/__xsp64tmp.
at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)`

**Comment by mirraj2** [comment]
This is just bad API design.  If someone passes you a File object, just save to that File.  Don't save to a different file.

**Comment by coobird** [comment]
@mirraj2, in hindsight, yes, this was a bad choice. However, changing this behavior would be a fairly big behavioral change of the library, so I'll have to do this in a version like 0.5.0.

This issue has been superseded by #186.
