### ISSUE TITLE
Stripes after creating thumbnail

### ISSUE THREAD

**Issue by ppasler** [coobird/thumbnailator#98]
Hey there,

we use the thumbnailator to scale images to a max-width or max-height (50px x 50px), but keeping the aspect ratio. For some reason, some scaled images have ugly stripes.

This is how we do it:

``` java
private static final int ICON_MAX_WIDTH = 50;

private static final int ICON_MAX_HEIGHT = 50;

public static byte[] createIconFromImageAsByteArray(final InputStream imageStream) throws IOException {
    final ByteArrayOutputStream baos = new ByteArrayOutputStream();
    Thumbnails.of(imageStream).width(ICON_MAX_WIDTH).height(ICON_MAX_HEIGHT).keepAspectRatio(true).outputFormat("png").toOutputStream(baos);
    return baos.toByteArray();
}
```

This is the original image
![google](https://cloud.githubusercontent.com/assets/6583084/17021142/2b2117f6-4f46-11e6-9dc7-44eb3a426c0c.png)

This is the generated thumbnail
![google png_scaled](https://cloud.githubusercontent.com/assets/6583084/17021153/43ed7856-4f46-11e6-86f1-c9bc21cffe2e.png)

Maybe we are missing some option?
Thanks in advance,
paul

**Comment by euleule** [comment]
Hi @ppasler ,

this relates to #26 and the suggested fix works fine for us.

Best regards,
Robert

**Comment by ppasler** [comment]
Thanks @euleule,

didn't relate these issues. Good job!

regards, paul
